"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../src/main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

# 32-bit only: wxPython 2.8.11.0 (mac-unicode) / Carbon (32-bit only)
OPTIONS['plist'] = {'LSPrefersPPC': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
