# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys

# TODO: Use py2exe to support building on Windows
if sys.platform != 'darwin':
    exit('This build script can only run on Mac OS X.')

APP_NAME = 'Crystal Web Archiver'
VERSION_STRING = '1.0'
FORCE_32_BIT = True     # wxPython 2.8.11.0 (mac-unicode) / Carbon (32-bit only)

PLIST = {
    'CFBundleDocumentTypes': [
        # Associate application with .crystalproj files
        {
            'CFBundleTypeExtensions': ['crystalproj'],
            #'CFBundleTypeIconFile': 'crystalproj.icns',
            #'CFBundleTypeName': 'net.dafoster.crystal.crystalproj'
            'CFBundleTypeRole': 'Editor',
            'LSTypeIsPackage': True,
        },
    ],
    'CFBundleIdentifier': 'net.dafoster.crystal',
    'CFBundleShortVersionString': VERSION_STRING,
    'CFBundleSignature': 'CrWA',
    'CFBundleVersion': VERSION_STRING,
    'LSPrefersPPC': FORCE_32_BIT,
    'NSHumanReadableCopyright': u'Copyright © 2010-2011 David Foster',
}
if FORCE_32_BIT: PLIST['LSArchitecturePriority'] = ['i386']

setup(
    name=APP_NAME,
    app=['../src/main.py'],
    data_files=[],
    options={'py2app': {
        'argv_emulation': True,
        'plist': PLIST,
        'prefer_ppc': FORCE_32_BIT,
    }},
    setup_requires=['py2app'],
)
